repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      files: .*\.py$
    # Run the formatter.
    - id: ruff-format
      files: .*\.py$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.14.1'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    files: ^src/.*\.py$  #